# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[aws]
disabled = true

[azure]
disabled = true

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1

[docker_context]
disabled = true

[gcloud]
disabled = true

[git_commit]
disabled = false

[golang]
disabled = false

[kubernetes]
disabled = true

[terraform]
disabled = true

[ruby]
disabled = true

[nodejs]
disabled = true

[time]
disabled = false
