[aws.region_aliases]
eu-west-1 = "ie"
us-east-1 = "va"

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1

[git_commit]
disabled = false

[golang]
disabled = false

[kubernetes]
disabled = false

[terraform]
disabled = false

[time]
disabled = false
