[aws.region_aliases]
eu-west-1 = "ie"
us-east-1 = "va"

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1

[env_var]
variable = "HEROKU_CLOUD"
default = "default"
disabled = false
prefix = "heroku:"
style = "bold purple"

[git_commit]
disabled = true

[golang]
disabled = true

[kubernetes]
disabled = false

[terraform]
disabled = false

[time]
disabled = false
