#!/bin/bash

set -eux

root=$(cd $(dirname $0)/.. && pwd)

ln -svf $root/gitconfig $HOME/.gitconfig

ln -svf $root/bashrc $HOME/.bashrc
ln -svf $root/bash_profile $HOME/.bash_profile
ln -svf $root/fish $HOME/.config/fish
ln -svf $root/nvim $HOME/.config/nvim
ln -svf $root/starship.toml $HOME/.config/starship.toml

echo "==> Install plug for nvim"
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
